# Growth curve models

In this chapter, we extend the models we have looked at so far and include
quadratic effects for individuals and on the population level.

## Slides

```{=html}
<object data="slides/06_growth_curve/06_growth_curve.pdf" type="application/pdf" width="100%" height="500px">
  <p>
    Unable to display PDF file. <a href="slides/06_growth_curve/06_growth_curve.pdf">Download</a> instead.
  </p>
</object>
```

## Exercises

### Exercise 1 {-}

The following exercise is strongly inspired by this chapter:
https://embraceuncertaintybook.com/longitudinal.html#the-elstongrizzle-data.

* Load the data set \texttt{elstongrizzle.dat} into R; data are from a dental
  study measuring the lengths of the ramus of the mandible (mm) in 20 boys at 8,
  8.5, 9, and 9.5 years of age

* Plot the individual data points for each subject either as a spaghetti plot
  and/or as a panel plot

* Fit a random slope model to the data; how would you interpret the correlation
  parameter in the model?

* Recenter your time variable, so that zero means ``8 years old''

* Refit your random slope model; try to explain why and how the correlation
  parameter changes

* Look at the caterpillar plots for the random slope model with and without
  recentered time variable; why do they look different?

* Create a shrinkage plot plotting the individual intercept as a function of the
  individual slopes

* Add individual and quadratic time effects to your model; test this model
  against the random slope model

* Look at the profiles for the random effects for the quadratic model; what
  would you conclude?


```{r ex06, results = "hide", class.source = "fold-hide", fig.show = "hide"}

library(lme4)
library(lattice)

# Read and visualize data

dat <- read.table("data/elstongrizzle.dat", header = TRUE)
dat$subject <- factor(dat$subject)

xyplot(ramusht ~ age, dat, groups = subject,
       type = c("b", "g"),
       xlab = "Age (yr)",
       ylab = "Ramus bone length (mm)")

xyplot(ramusht ~ age | subject, dat,
       type = c("g", "p", "r"),
       aspect = "xy",
       index.cond = function(x,y) coef(lm(y ~ x)) %*% c(1, 8),
       xlab = "Age (yr)",
       ylab = "Ramus bone length (mm)")

# Anything quadratic?
xyplot(ramusht ~ age | subject, dat,
       type = c("g", "p", "spline"),
       aspect = "xy",
       index.cond = function(x,y) coef(lm(y ~ x)) %*% c(1, 8),
       xlab = "Age (yr)",
       ylab = "Ramus bone length (mm)")

# Random slope model
m1 <- lmer(ramusht ~ age + (age | subject), dat)
summary(m1)

dotplot(ranef(m1), scales = list(x = list(relation = "free")))[[1]]

# Centering the time variable (at a value of interest)

dat$time <- dat$age - 8

m2 <- lmer(ramusht ~ time + (time | subject), dat)
summary(m2)

dotplot(ranef(m2), scales = list(x = list(relation = "free")))[[1]]

# Shrinkage plot

df     <- coef(lmList(ramusht ~ time | subject, dat))
fclow  <- subset(df, `(Intercept)` < 50)
fchigh <- subset(df, `(Intercept)` > 50)
cc1    <- as.data.frame(coef(m2)$subject)
names(cc1) <- c("A", "B")

df <- cbind(df, cc1)
ff <- fixef(m2)

with(df,
  xyplot(`(Intercept)` ~ time, aspect = 1,
    x1 = B, y1 = A,
    panel = function(x, y, x1, y1, subscripts, ...) {
        panel.grid(h = -1, v = -1)
        x1 <- x1[subscripts]
        y1 <- y1[subscripts]
        larrows(x, y, x1, y1, type = "closed", length = 0.1,
                angle = 15, ...)
        lpoints(x, y,
                pch = trellis.par.get("superpose.symbol")$pch[2],
                col = trellis.par.get("superpose.symbol")$col[2])
        lpoints(x1, y1,
                pch = trellis.par.get("superpose.symbol")$pch[1],
                col = trellis.par.get("superpose.symbol")$col[1])
        lpoints(ff[2], ff[1], 
                pch = trellis.par.get("superpose.symbol")$pch[3],
                col = trellis.par.get("superpose.symbol")$col[3])
        ltext(fclow[,2], fclow[,1], row.names(fclow), adj = c(0.5, 1.7))
        ltext(fchigh[,2], fchigh[,1], row.names(fchigh), adj = c(0.5, -0.6))
    },
    key = list(space = "top", columns = 3,
               text = list(c("Mixed model", "Within-subject", "Population")),
               points = list(col = trellis.par.get("superpose.symbol")$col[1:3],
                             pch = trellis.par.get("superpose.symbol")$pch[1:3]))
  )
)


# Fitting a quadratic trend

m3 <- lmer(ramusht ~ time + I(time^2) + (time + I(time^2) || subject), dat)
summary(m3)

dotplot(ranef(m3), scales = list(x = list(relation = "free")))[[1]]

anova(m2, m3)

# Profiles
pm3 <- profile(m3, which = "theta_")

xyplot(log(pm3))
densityplot(log(pm3))
splom(log(pm3))

confint(pm3)
```

