---
title: "Course on Mixed-effects Models"
author: "Nora Wickelmaier"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
output:
  bookdown::gitbook:
    code_folding: show
bibliography: literature/lit.bib
biblio-style: apalike
link-citations: yes
csl: norsk-apa-manual.csl
github-repo: https://github.com/nwickel/mixed_models/
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(warning = FALSE, message = FALSE)
```
# Course information {-}

This is an online book accompanying a course on mixed-effects models taught to
PhD students at the Leibniz-Institut für Wissensmedien (IWM) in Tübingen.

The data sets used in the examples and exercises can be downloaded
[here](https://github.com/nwickel/mixed_models/tree/master/data).

## Desirable background knowledge {-}

Alle examples in this course are worked out in [R](https://www.r-project.org/).
Introductory knowledge in R is therefore a prerequisite. Apart from this, I will
assume that you have some kind of workflow how to use R with a text editor
(e.g., [Vim](https://www.vim.org/)) or an IDE (e.g.,
[RStudio](https://posit.co/downloads/)).

It is further assumed that you have attended at least one introductory
statistics course (level "Statisik I" and "Statistik II" usually taught in
psychology curricula at German universities). That means you should be familiar
with concepts like random variables, statistical distributions like the normal
distribution, $t$ distribution, Binomial distribution, etc., and hypothesis
testing. Some background in regression analysis is helpful, but we will cover
the basics in this course.

If you feel like these concepts could be a bit more "present" in your head, you
can go through the [first chapter](https://vasishth.github.io/Freq_CogSci/some-important-facts-about-distributions.html)
in the online book by @Vasishth2022. There will be time to ask questions about
the concepts in the sessions, but we will not have time to go through all of
them together.

Hopefully, these resources will help to get everybody on the same page. If you
need more support or materials, just let me know.

## Overview of dates and topics {-}

### WS 2024/25 {-}

| Date       | Topic                                    |
| ---------- | ---------------------------------------- |
| 28.10.2024 | Simple and multiple regression           |
| 11.11.2024 | Generalized linear models                |
| 25.11.2024 | Pre/post measurements                    |
| 09.12.2024 | Longitudinal data                        |
| 13.01.2025 | Repeated measures                        |
| 27.01.2025 | Growth curve models                      |
| 10.02.2025 | Crossed random effects                   |

### SS 2025 {-}

| Date       | Topic                                    |
| ---------- | ---------------------------------------- |
| 14.04.2025 | Random effects for within-subject designs|
| 28.04.2025 | Contrast coding                          |
| 12.05.2025 | Generalized linear mixed-effects model   |
| 26.05.2025 | Multilevel models                        |
| 23.06.2025 | Data simulation in R                     |
| 07.07.2025 | Power simulation longitudinal data       |
| 21.07.2025 | Power simulation (G)LMM within design    |


## Literature {-}

This course is mostly built on the following books and papers:

* @Alday2025

* @Baayen2008

* @Bates2015

* @GelmanHill2020

* @Vasishth2022

* @Wickelmaier2022

